### PR TITLE
Updated entry for Sonatina Symphonic Orchestra

### PR DESCRIPTION
**Pull request by peastman**
I updated the version information, added a download link, and rewrote the description.

### CODE REVIEW

**Comment by peastman** [comment]
Can someone merge this?  Thanks!

**Comment by peastman** [comment]
Thanks!  I had given up on it. :)

This PR is itself rather out of date at this point.  I just released version 3.8.  Is it ok if I create another PR to update it?  I'd also like to add an audio demo.

**Comment by DSmolken** [comment]
Sure, please do another PR, I promise to not be so late this time...

**Comment by peastman** [comment]
> Sure, please do another PR, I promise to not be so late this time...

I'm afraid you missed your deadline.  It's been five months since I opened #47.  Do you think it could maybe be merged? :)

**Pull request merged**
