### PR TITLE
Bass metadata

### PR DESCRIPTION
**Pull request by kmturley**
As discussed in Discord. There is instrument metadata missing which would improve the user experience of discovering sfz instruments.

Instruments yaml could include:
- Audio preview file url
- Image preview file url
- Download urls (High-quality, compact/compressed)
- Cost attribute ($ in dollars)
- Compatibility attribute ('Bassmidi','sforzando','sfizz')
https://github.com/sfzinstruments/sfzinstruments.github.io/blob/master/_data/sfz/instruments.yml

This PR adds the appropriate metadata for Bass instruments only. If this looks good I can continue to add more metadata for the other instrument types.

### CODE REVIEW

**Comment by redtide** [comment]
Honestly, beside the image and audio sample previews I don't find any advantage on some additional details.

I started this project as a simple list of instruments (mainly interested in the free ones) with the hope some other people could join to help adding more, but after months there was not much interest.

With these additions you are proposing to add more maintenance without any apparent advantages (an user can simply go to the site to see the details):
- cost: even it could be useful for them to compare prices, this needs to be kept up to date
- compatibility: who is going to keep this updated other then tested? An update could break some kind of functionality in some particular sampler

Downloads information, including audio format and sample rate should be already available for addition, no additional metadata should be needed.

I noticed some version number was added. It should be precise, e.g. "1.001" instead "1": the number should be the same as the release version (so also containing strings, like "-beta3"), otherwise there would be no difference between some 1.001, 1.002 and so on.

**Comment by kmturley** [comment]
Appreciate the feedback!

- version - I had left major versions only because the versioning did not follow standard https://semver.org. Have updated to use the full version string
- audio/image - I thought explicit urls was better than implicit, otherwise if the instruments.yaml was parsed by another app then it would need the same url logic. I could remove them if you think they are unnecessary.
- cost - @DSmolken had mentioned that introducing cost would allow sfzinstruments to expand to include paid instruments. It would help instrument creators to make income from their sfz instruments. I agree that it would also make sfz be perceived as a more mature format if there are paid/quality instruments, not just free side-projects.
- compatibility - @DSmolken also suggested as there are inconsistencies in support across different players. It would be good to start documenting the inconsistencies somewhere.

New attributes will create more overhead in management yes, but how often are instruments updated? Anyone can create a PR to update their attributes if they go out-of-date, the burden doesn't need to be on you.

Overall the purpose of adding new attributes is to show essential information to users, which they need in order to decide whether to download the instrument or not. Rather than have them search each third-party which may or may-not even have the information listed. Collect and show before they commit to download.

- Current user experience - Select instrument, Have to click through to website to try and find out more information about cost, compatibility and download links.
- Proposed user experience - Select instrument, See cost/compatibility upfront, click a button to download the instrument directly without needing to open other pages.

As shown in my sfz website example, you can then use these attributes to filter/sort instruments in a single place e.g. all instruments with CC-0 license:
https://kmturley.github.io/sfz-website/instruments/?license=cc0-1.0

Or all instruments with cost=0, or compatibility=sfizz. The user experience benefits 10x when using filters and searches by bringing the metadata forward into one place.

**Comment by DSmolken** [comment]
Yeah, cost or at least a free/commercial flag would be beneficial to me as it'd give me a way to add my commercial instruments without annoying the people who are just looking for free stuff... which would also make sfz look more "serious" and hopefully make the free instruments more appealing by association.

Compatibility I don't think is quite as important, but it'd help people with mobile devices or otherwise unsupported systems avoid wasting time on Sforzando-specific instruments (or at least know they might have to simplify or redo stuff to use the samples). Sorting out the super-basic SFZ1 instruments from slightly more advanced ones that work in BassMIDI would be more of a pain but we can ask one of the BassMIDI users who knows the answers to do a pull request to fill them out. So, adding compatibility would have some user experience upside, even if we only do the low-hanging fruit of marking Sforzando-specific instruments as such.

**Comment by redtide** [comment]
> version - I had left major versions only because the versioning did not follow standard https://semver.org/

Not anyone uses Semantic Versioning specification, the only way is to report the exact string, without expecting to use it to make any kind of data processing, as is now it's just for displaying information.

> I thought explicit urls was better than implicit, otherwise if the instruments.yaml was parsed by another app

Who tells you that that wasn't done by purpose?
1. I want less but useful information as possible in the db, so also less work
2. I don't want to provide any app (I wonder which app should care about our assets) about data to add download traffic we don't need
3. Automatic

> but how often are instruments updated? Anyone can create a PR to update their attributes if they go out-of-date, the burden doesn't need to be on you

I'm not bothered only about the maintenance addition, OTOH I wouldn't take care of it anyway, see below.

@DSmolken,

> Yeah, cost or at least a free/commercial flag would be beneficial to me

I would solve this with a "Commercial" license type, same as we did in sfzformat.com in the software section; commercial instruments could be added already.

About compatibility I feel a lot of cons:
- incomplete information: giving the poor attention on this project I don't expect much testing
- information out of sync
- false information: I would have to merge (a lot of?) PRs blindly (trust) with the risk to get bad feedback from users

So the consequence might be people reporting problems, if not complaining about them (more PRs. more issues).

> but we can ask one of the BassMIDI users who knows the answers to do a pull request to fill them out

then this should be done from time to time after some new instruments will be added.

IMHO this should be only provided by authors in their website' instrument details, not us.

Anyway, if you think the PR is OK as is, feel free to take care of it and merge it, that will mean to me that you guys will take care of the additional work, I'm only interested to add missing instruments than spend time to add something that from my POV will require more time and probably will cause more problems than benefits.
In that case I noticed another thing: please first remove `cost: 0` data in the db, it's not needed.

**Comment by redtide** [comment]
In short my preference would be:
- remove cost, compatibility, image and audio from the db
- add audio files using the current method and images in a similar logic
- a single commit; if you need to fix or add other related stuff use `force push` over the previous

**Comment by kmturley** [comment]
Have removed the additional attributes for now.

You can squash all commits when merging a GitHub PR:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by DSmolken** [comment]
So now we're just adding more instruments to the list, not adding any attributes?

**Pull request merged**
