### PR TITLE
Fixes for instrument urls

### PR DESCRIPTION
**Pull request by kmturley**
Fixes several urls, and updates some to point at instrument landing pages instead of a download

### CODE REVIEW

**Comment by redtide** [comment]
Looks like you have an old copy of the code, the Karoryfer links are correct in the current tree

**Comment by kmturley** [comment]
Ah yes. My fork main branch was out of date. Have updated

**Comment by redtide** [comment]
I needed some time to remember what was the initial intention to link to releases instead to the project page; there is a main issue with Github with their compressed downloads that don't include git submodules. Now the green button is labeled "Code" where it was "Clone or Download" and having the releases link on the same page seems to me a bit confusing for people that don't know what git/branches stuff is, so for projects having at least a release I prefer to point to it instead.
Git submodules might seem strange for sfz instruments but not impossible and I'm not going to check for exceptions. Other than that the main branch might contain experimental features that might not work.

**Comment by kmturley** [comment]
💯 agree for not confusing the user.

My understanding was that:
- `url` was for linking to a project landing page to learn more
- `downloads` was for linking to actual files

So I was planning to submit a PR to add direct download links to releases under downloads

**Pull request merged**
